[package]
name = "supernova"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2.1"
miette = { version = "7.5.0", features = ["fancy"] }
num-bigint = "0.4.6"
phf = { version = "0.11.3", features = ["macros"] }
thiserror = "2.0.11"
